feat(bybit): Add spot support and migrate to API V5
bmoscon/cryptofeed pull request #1017
Opened 2024-03-07 11:39 UTC by kosmodromov

This PR adds support for the spot market on Bybit exchange and migrate to V5 API.

Updated market data endpoints:
- Trades: spot, perps, futures
- L2_book: spot, perps, futures 
- Candles: spot, perps, futures
- Tickers: perps, futures
- Funding: perps
- Index: perps, futures
- Open Interest: perps, futures
- Liquidations: perps, futures

Only linear futures is supported. No inverse futures support.
Private endpoints remain unmodified.

```
from cryptofeed import FeedHandler
from cryptofeed.exchanges import Bybit
from cryptofeed.defines import TRADES, L2_BOOK, BID, ASK, CANDLES, LIQUIDATIONS, TICKER, FUNDING, OPEN_INTEREST, INDEX, FILLS, ORDER_INFO

async def book(d, receipt_timestamp):
    print(f'{receipt_timestamp} for {d.exchange} - {d.symbol}, with {len(d.book)} entries. bid/ask: {d.book.bids.index(0)[0]}/{d.book.asks.index(0)[0]}, delta: {len(d.delta[BID]) + len(d.delta[ASK])} entries')

async def anything(d, receipt_timestamp):
    print(d)

def main():
    f = FeedHandler()
    f.add_feed(Bybit(symbols=["ETH-USDT", "ETH-USDT-PERP"], channels=[TRADES, L2_BOOK], callbacks={TRADES: anything, L2_BOOK: book}))
    f.add_feed(Bybit(symbols=["BTC-USDT-PERP", "XRP-USDC-PERP"], channels=[TRADES, L2_BOOK, FUNDING, OPEN_INTEREST, INDEX],callbacks={TRADES: anything, L2_BOOK: book, FUNDING: anything, OPEN_INTEREST: anything, INDEX: anything}))
    f.run()

if __name__ == '__main__':
    main()
```

- [x] - Tested
- [x] - Changelog updated
- [x] - Tests run and pass
- [x] - Flake8 run and all errors/warnings resolved
- [ ] - Contributors file updated (optional)

2024-03-31 17:19 UTC, bmoscon requested changes
I left a comment about part of the code I'm unsure about. Other than that, looks ready to merge once thats resolved

2024-03-31 17:19 UTC, bmoscon commented
@kosmodromov - thanks for the PR -  just one question for you, then we can merge this.

2024-04-01 11:23 UTC, kosmodromov commented on cryptofeed/exchanges/bybit.py
> +        # Bybit spot and USDT perps use the same symbol name. To distinguish them, use a slash to separate the base and quote.
Here it adds a slash to spot pairs in order to build proper normalized dict (as linear and spot symbols are identical)

https://github.com/kosmodromov/cryptofeed/blob/8d271a5e63f5bed3bf084e0369eb0b140849b304/cryptofeed/exchanges/bybit.py#L104-L113

Then in `message_handler` it gets the market (spot | perp) from `url` line and then passes `market` parameter to a functions _candle, _trade and _book. These functions receive spot and perp pair information from the websocket, where both are formatted as 'BTCUSDT'

https://github.com/kosmodromov/cryptofeed/blob/8d271a5e63f5bed3bf084e0369eb0b140849b304/cryptofeed/exchanges/bybit.py#L212-L219

Then `convert_to_spot_name` function adds slash in order to properly use normalized dict later in the code for spot pairs.

This approach may seem complex, but I haven't found a clearer way to implement it.
 
Short answer on your question - no, no needs to add anything special to subscribe.

2024-04-01 22:54 UTC, bmoscon approved these changes

2024-04-01 22:54 UTC, merged