add support for binance_delivery api (dapi)
bmoscon/cryptofeed pull request #329
Opened 2020-11-16 15:02 UTC by txu2014

* Feature: new exchange: Binance Delivery.
### Description of code - what bug does this fix / what feature does this add?

- [ ] - Tested
- [ ] - Changelog updated
- [ ] - Contributors file updated (optional)

2020-11-16 15:10 UTC, bmoscon commented
please undo the formatting changes made that shorten lines you didn't touch.

2020-11-16 15:11 UTC, bmoscon requested changes
undo formatting changes to un-modified code

2020-11-16 16:13 UTC, txu2014 commented
> undo formatting changes to un-modified code

removed duplicated lines caused by line wrapping.

2020-11-21 14:12 UTC, bmoscon requested changes

2020-11-21 14:12 UTC, bmoscon commented on cryptofeed/exchange/binance_delivery.py
> +from cryptofeed.defines import BINANCE_FUTURES, BINANCE_DELIVERY, OPEN_INTEREST, TICKER
binance_futures import is not used in this file, please remove

2020-11-21 14:12 UTC, bmoscon commented on cryptofeed/pairs.py
> -            data.extend(requests.get(f"https://www.deribit.com/api/v2/public/get_instruments?currency={c}&expired=false&kind={k}").json()['result'])
undo formatting

2020-11-21 14:12 UTC, bmoscon commented on cryptofeed/pairs.py
> +        _exchange_info[HUOBI_DM]['short_code_mappings'][f"{e['symbol']}_{mapping[e['contract_type']]}"] = e[
undo formatting

2020-11-21 14:12 UTC, bmoscon commented on cryptofeed/rest/binance_futures.py
> +                return requests.get(
undo formatting

2020-11-21 14:12 UTC, bmoscon commented on cryptofeed/rest/binance_futures.py
> +                    LOG.warning(
undo formatting

2020-11-21 14:12 UTC, bmoscon commented on cryptofeed/standards.py
> +    elif exchange in {HUOBI, HUOBI_DM, HUOBI_SWAP, BITFINEX, COINBENE, DERIBIT, BINANCE, BINANCE_US, BINANCE_FUTURES,
undo formatting

2020-11-25 21:56 UTC, bmoscon commented
the binance delivery code would also need to be in its own file, please change that. If you do not want to make these changes, I can create a new branch with these changes and list you as the co-author of the changeset.

2020-11-29 13:37 UTC, merged

2020-11-29 13:46 UTC, bmoscon commented
@txu2014 - thanks for the PR!