Support OKEx options
bmoscon/cryptofeed pull request #397
Opened 2021-01-17 00:46 UTC by olibre

### Support OKEx options

Hi Bryant. I have move out some features from the big PR about the AsyncConnection refactoring. This is one of the features.

The feature has been successfully tested in my other branch.
But this branch has not been tested.
Please, could you test this?

- [ ] - Tested
- [x] - Changelog updated
- [ ] - Tests run and pass
- [ ] - Flake8 run and all errors/warnings resolved
- [ ] - Contributors file updated (optional)

2021-01-22 23:37 UTC, bmoscon commented on cryptofeed/exchange/okcoin.py
> +        dash_count = pair.count("-")
users can specify other pair separators in symbols.py

2021-01-22 23:38 UTC, bmoscon requested changes
only thing I'd change is the pair separator which is not always going to be "-"

2021-01-25 23:23 UTC, bmoscon commented
@olibre if you dont have the time to resolve that outstanding issue, let me know and I can fix it myself post merge

2021-01-25 23:24 UTC, merged

2021-01-25 23:24 UTC, bmoscon commented
actually I went to use the new function you added to utils for something else, so I just merged it and will resolve myself :) thanks for the PR!

2021-02-01 23:08 UTC, olibre commented
Sorry Bryant, I was busy (I am still very busy on other projects...)

2021-02-01 23:09 UTC, bmoscon commented
@olibre no worries, happens to everyone :)