Victoriametrics backend
bmoscon/cryptofeed pull request #444
Opened 2021-03-18 09:33 UTC by abashinfection

### VictoriaMetrics Backend

This PR aims to add support for VictoriaMetrics backend storage.

VictoriaMetrics supports multiple protocols for data ingestion.
In this implementation we format data in InfluxDB Line Protocol and send it over TCP/UDP sockets.

All Callback classes have been implemented: trades, tickers, funding, order book, open interest, liquidations, market info, transactions. For Order Book processing and serialisation, VictoriaMetrics backend classes borrow the same implementation as the InfluxDB backend.

A demo script is included to test the new VictoriaMetrics backend. This script has been tested with VictoriaMetrics v1.55.1 docker image with CL option `-influxListenAddr :TCP_PORT`

- [x] - Tested
- [x] - Changelog updated
- [x] - Tests run with one failure on Bitmex REST API (code not changed by this PR)
- [x] - Flake8 run and all errors/warnings resolved
- [ ] - Contributors file updated (optional)

2021-03-22 23:43 UTC, bmoscon requested changes

2021-03-22 23:43 UTC, bmoscon commented on cryptofeed/backends/victoriametrics.py
> +    default_key = 'transactions'
Can we add one for candles?

2021-03-22 23:43 UTC, bmoscon commented
@abashinfection - thanks for the PR! Just one missing backend (Candles) can you add that and then I will merge this?

2021-03-24 15:41 UTC, abashinfection commented on cryptofeed/backends/victoriametrics.py
> +    default_key = 'transactions'
Done and tested!

2021-03-24 15:45 UTC, abashinfection commented
<img width="1680" alt="Screenshot 2021-03-24 at 16 43 26" src="https://user-images.githubusercontent.com/29240616/112339708-34a88180-8cc0-11eb-8090-6ff4313ea01f.png">

Quick Dashboard built with Cryptofeed+VictoriaMetrics+Grafana

2021-03-24 16:55 UTC, bmoscon approved these changes

2021-03-24 16:55 UTC, merged