Binance futures auth for User data streams
bmoscon/cryptofeed pull request #550
Opened 2021-07-07 14:24 UTC by twmeggs

### Allows use of USER_DATA streams from Binance USDT futures.

The subscription name is `USER_DATA`, which produces five user-account related streams: account updates, order updates, margin calls, account config changes, and `listenKey` expiration (see [docs](https://binance-docs.github.io/apidocs/futures/en/#user-data-streams)).

This pull request code implements callbacks to handle account updates (`ACCOUNT_UPDATE`) and order updates (`ORDER_INFO`)

- [x] - Tested
- [x] - Changelog updated
- [x] - Tests run and pass
- [x] - Flake8 run and all errors/warnings resolved
- [x] - Contributors file updated (optional)

2021-07-11 01:53 UTC, xiandong79 commented
what about a demo example? which has some expected output in its comments.

2021-07-11 08:44 UTC, Herklos commented
Nice job @twmeggs, can't wait to use it with cryptofeed

2021-07-11 14:11 UTC, bmoscon requested changes

2021-07-11 14:11 UTC, bmoscon commented on cryptofeed/exchange/binance_futures.py
> +        await self.callback(ACCOUNT_UPDATE,
it doesnt look like you actually are returning any data here? Wouldnt you want to return information about the account here too?

2021-07-11 14:11 UTC, bmoscon commented on cryptofeed/feed.py
> -
i like this whitespace

2021-07-11 14:11 UTC, bmoscon commented on cryptofeed/feed.py
> -
same here, i think its easier to read with the whitespace in the comments

2021-07-11 14:11 UTC, bmoscon commented on cryptofeed/standards.py
> -
unclear why this was removed, please put it back

2021-07-11 14:12 UTC, bmoscon commented
@twmeggs overall - looks good. there are many places where you removed blank lines in comments - please undo those changes. There was one other comment about a callback, so let  me know if i missed something there

2021-08-05 21:40 UTC, bmoscon commented
@twmeggs sorry, I think this has divered too much for me to fix it. There is also the issue with the account_update callback that does nothing (it just returns a timestamp really). I don't know how to fix that. If you want to resolve these issues or rework this in a new branch, that would be wonderful. If not, that's ok to. I'm going to close this since it is un-mergeable as is. If you want to re-open this or open a new PR later, thats fine too

2021-08-05 21:40 UTC, closed without merging