feeds http_proxy
bmoscon/cryptofeed pull request #576
Opened 2021-07-24 14:33 UTC by jinusean

### Description of code - what bug does this fix / what feature does this add?

- [x] - Tested
- [x] - Changelog updated
- [x] - Tests run and pass
- [x] - Flake8 run and all errors/warnings resolved
- [x] - Contributors file updated (optional)

Enables a `http_proxy` param in Feed that is used by HttpProxy/HttpPoll when making GET calls.

2021-07-24 14:39 UTC, jinusean commented
Should aid in overcoming issues described in https://github.com/bmoscon/cryptostore/issues/156

2021-07-24 14:47 UTC, bmoscon requested changes
it looks like you've added a new library requirement, YARL. I'm not opposed to adding libraries if they are used, but if you are using it solely for type hinting - is it really necessary?

2021-07-25 02:14 UTC, jinusean commented on cryptofeed/feed.py
> +from aiohttp.typedefs import StrOrURL
Replaced YARL with aiohttp's typedef

2021-07-25 02:14 UTC, jinusean commented on cryptofeed/connection.py
> +from aiohttp.typedefs import StrOrURL
Replaced YARL with aiohttp's typedef

2021-07-25 02:15 UTC, jinusean commented
YARL was used by aiohttp but using the latter's type definitions is probably better.

Thanks!

2021-07-25 13:20 UTC, bmoscon approved these changes

2021-07-25 13:21 UTC, merged