Support for Open interest interval in Binance Futures
bmoscon/cryptofeed pull request #592
Opened 2021-08-03 14:07 UTC by jinusean

Allows polling interval for open interest in Binance Futures. 

- Fixed some syntax errors from previous merge. 
- Fixed HTTPConcurrentPoll to handle reconnects.

- [x] - Tested
- [x] - Changelog updated
- [x] - Tests run and pass
- [x] - Flake8 run and all errors/warnings resolved
- [ ] - Contributors file updated (optional)

2021-08-03 21:29 UTC, bmoscon commented on cryptofeed/connection.py
> +                with suppress(asyncio.exceptions.TimeoutError):
can you explain why this block of code is necessary?

2021-08-03 21:32 UTC, bmoscon commented on cryptofeed/exchanges/binance.py
> +            self.open_interest = {}
there isnt currently a defined `open_interest` method in the RestExchange class or the RestMixins, but there probably will be soon. Naming should be changed to _open_interest. I know this was here before you modified it, but now is as good a time as any to change it

2021-08-03 21:32 UTC, bmoscon requested changes
see previous comments

2021-08-07 00:13 UTC, bmoscon commented on cryptofeed/exchanges/binance.py
> +            self.open_interest = {}
this no longer applies, I changed the new to self._open_interest_cache, so just update the name here

2021-08-19 00:24 UTC, bmoscon commented
@jinusean are you able to make the requested changes?

2021-08-19 04:04 UTC, jinusean commented
Yes I've just pushed the relevant changes.

2021-08-19 12:09 UTC, bmoscon approved these changes

2021-08-19 12:09 UTC, merged