Adding ORDER_INFO, FILLS to huobi spot
bmoscon/cryptofeed pull request #791
Opened 2022-02-20 14:29 UTC by Acid3croco

### Description of code - what bug does this fix / what feature does this add?

- [X] - Tested
- [X] - Changelog updated
- [  ] - Tests run and pass
Error with type import 
```ModuleNotFoundError: No module named 'cryptofeed.types'```

- [X] - Flake8 run and all errors/warnings resolved

2022-02-20 14:54 UTC, bmoscon commented
@Acid3croco - if you have downloaded the source code to develop from, you need to run `python setup.py develop`. This will build the Cython data types into that file - `cryptofeed.types`. I'll take a look at what you have here, but I won't merge anything that is un-tested, so let me know when you're able to get that working and tested

2022-02-20 14:56 UTC, bmoscon requested changes

2022-02-20 14:56 UTC, bmoscon commented on cryptofeed/exchanges/huobi.py
> +    rest_endpoints = [
please undo this change - looks like the line did not change, but you used some tool that made a 1 line declaration into a 3 line.

2022-02-20 14:56 UTC, bmoscon commented on cryptofeed/exchanges/huobi.py
> +            base, quote = e['base-currency'].upper(
undo this formatting change

2022-02-20 14:56 UTC, bmoscon commented on cryptofeed/exchanges/huobi.py
> -            self._l2_book[pair] = OrderBook(self.id, pair, max_depth=self.max_depth)
undo this

2022-02-20 14:56 UTC, bmoscon commented on cryptofeed/exchanges/huobi.py
> +        self._l2_book[pair].book.bids = {
undo this

2022-02-20 14:57 UTC, bmoscon commented
@Acid3croco looks like a lot of changes that are just formatting changes. Please undo those and I'll take another look. Have a look at the contributing doc - https://github.com/bmoscon/cryptofeed/blob/master/CONTRIBUTING.md - under PRs it specifically calls out formatting changes like this.

2022-02-20 14:58 UTC, bmoscon requested changes

2022-02-20 14:58 UTC, bmoscon commented on cryptofeed/exchanges/huobi.py
> +        LOG.debug(f"{conn.uuid}: Received message: {msg}")
even in a debug scenario I dont think we want to log every message, that would be a massive amount of volume.

2022-02-20 15:00 UTC, Acid3croco commented
Hello, ima fix everything and will come back with something cleaner, thanks for the feedback

2022-03-12 22:59 UTC, xiva-wgt commented
- Tests run and pass
Error with type import, I may be missing something to execute them?
ModuleNotFoundError: No module named 'cryptofeed.types'

Before code import cryptofeed need add this code
import pyximport
pyximport.install(language_level=3)

2022-03-13 00:05 UTC, bmoscon commented
@xiva-wgt if you download the source code you need to run setup.py to build the cython modules

2022-03-19 23:33 UTC, bmoscon commented
@Acid3croco if you ever get back to this please open a new PR or re-open this one. Closing since this seems to be abandoned.

2022-03-19 23:33 UTC, closed without merging