Authenticated data channels support for redis (Streams and Sorted Sets)
bmoscon/cryptofeed pull request #853
Opened 2022-05-23 20:40 UTC by AlgoQ

Support for the authenticated data channels for Redis (Streams and Sorted Sets).

2022-05-23 20:41 UTC, AlgoQ commented
I will create another pull request for the other backends when I find the time (probably later this week).

2022-07-28 14:06 UTC, bmoscon requested changes

2022-07-28 14:06 UTC, bmoscon commented on cryptofeed/backends/rabbitmq.py
> +from parso import ParserSyntaxError
this appears to not be used

2022-07-28 14:08 UTC, bmoscon approved these changes

2022-07-28 14:08 UTC, merged