Use hasattr() for aggregate callbacks
bmoscon/cryptofeed pull request #999
Opened 2023-11-21 01:04 UTC by noahfrn

`callable()` returns True for classes that override the __call__ method - this change uses `hasattr` to explicitly determine if the given handler:
- Is a  class
- Has a start method
- Has a stop method

2024-01-07 15:53 UTC, bmoscon requested changes

2024-01-07 15:53 UTC, bmoscon commented on cryptofeed/backends/postgres.py
> +import logging
everything else is using the log.py file functionality, why did you opt to use the logging package here?

2024-02-10 22:45 UTC, bmoscon commented
feel free to re-open this if you have time to update the PR. closing for now

2024-02-10 22:45 UTC, closed without merging

2024-02-24 16:50 UTC, noahfrn commented
Apologies for the delay on this, have re-opened #1013 with just the aggregate callback change.